apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: db-user-pas
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 10000000"]
      volumeMounts:
        - name: secret-volume
          mountPath: /mydata