apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      env:
        - name: myusername
          valueFrom:
            secretKeyRef:
              name: db-user-pas
              key: username.txt
        - name: password
          valueFrom:
            secretKeyRef:
              name: db-user-pas
              key: password.txt