apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}
spec:
  selector:
    app: {{.Values.deployAccount.name}}
  type: {{.Values.service.type}}
  ports:
    - name: echo
      port: {{.Values.service.port}}
      targetPort: {{.Values.deployAccount.containers.port}}
      nodePort: {{ .Values.service.nodePort}}
      protocol: {{.Values.service.protocol}}