apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: nginx
      volumeMounts:
        - mountPath: /redis-master
          name: config
  volumes:
    - name: config
      configMap:
        name: redis-config
        items:
          - key: game.properties
            path: redis.conf