apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: app
  type: NodePort
  ports:
    - name: echo
      port: 3030
      targetPort: 3030
      nodePort: 30040
      protocol: TCP