apiVersion: v1
kind: Pod
metadata:
  name: bookservervolume
spec:
  volumes: 
    - name: "bookservervolume"
      hostPath: 
        path: "/var/log"
  containers:
    - image: anisurrahman75/book-server-api:v1.4
      name: bookservervolume
      volumeMounts:
        - mountPath: "/var/log"
          name: "bookservervolume"
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 3030
          name: http
          protocol: TCP