apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
#  completions: 10
#  parallelism: 1
  template:
    metadata:
      name: countdown
    spec:
      containers:
        - name: counter
          image: centos:7
          command: ["ls","/anisur"]
      restartPolicy: OnFailure
