apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-api1
  labels:
    app: my-backend-api1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-backend-api1
  template:
    metadata:
      labels:
        app: my-backend-api1
    spec:
      containers:
        - name: my-backend-api1
          image: anisurrahman75/book-server-api:v1.4
          ports:
          - containerPort: 80

