# pod-configmap-env.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c","sleep 600"]
      env:
        # Define the environment variable
        - name: COLORNAME # Notice that the case is different here from the key name in the configMap. works like variable
          valueFrom:
            configMapKeyRef:
              name: special-config # The configMap this value comes from
              key: color.name # The key to fetch
        - name: COLORCODE
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: color.code