apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: nginx-rs
    labels:
        app: nginx-app
spec:
    replicas: 10
    selector: 
        matchLabels: 
            app: nginx-app
            tier: frontend
        matchExpressions:
            - {key: tier, operator: In, values: [frontend]}
    template:
        metadata:
            name: nginx-pod
            labels:
                app: nginx-app
                tier: frontend
        spec:
            containers:
            - name: nginx-container
              image: nginx
              ports: 
                - containerPort: 80