apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-backend-api
spec:
  selector:
    app: my-backend-api
  type: NodePort
  ports:
    - nodePort: 31000
      port: 3030
      targetPort: 3030