apiVersion: v1
kind: Pod
metadata:
  name: lebelbookserver
  labels:
    app: bookserver
    env: prod
    ver: "1"
spec:
  containers:
    - image: anisurrahman75/book-server-api:v1.4
      name: lebelbookserver
      livenessProbe:
        httpGet:
          path: /api/books
          port: 3030
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
      - containerPort: 3000
        name: http
        protocol: TCP